# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from lagrl.sandbox.proto import sandbox_pb2 as lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in lagrl/sandbox/proto/sandbox_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SandboxStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/lagrl.sandbox.v1.Sandbox/CreateSession',
                request_serializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.Session.FromString,
                _registered_method=True)
        self.Execute = channel.unary_unary(
                '/lagrl.sandbox.v1.Sandbox/Execute',
                request_serializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.ExecuteRequest.SerializeToString,
                response_deserializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.ExecutionReference.FromString,
                _registered_method=True)
        self.GetExecution = channel.unary_unary(
                '/lagrl.sandbox.v1.Sandbox/GetExecution',
                request_serializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.ExecutionReference.SerializeToString,
                response_deserializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.ExecutionResult.FromString,
                _registered_method=True)
        self.DestroySession = channel.unary_unary(
                '/lagrl.sandbox.v1.Sandbox/DestroySession',
                request_serializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.DestroySessionRequest.SerializeToString,
                response_deserializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.DestroySessionResult.FromString,
                _registered_method=True)


class SandboxServicer:
    """Missing associated documentation comment in .proto file."""

    def CreateSession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Execute(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DestroySession(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SandboxServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.CreateSessionRequest.FromString,
                    response_serializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.Session.SerializeToString,
            ),
            'Execute': grpc.unary_unary_rpc_method_handler(
                    servicer.Execute,
                    request_deserializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.ExecuteRequest.FromString,
                    response_serializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.ExecutionReference.SerializeToString,
            ),
            'GetExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.GetExecution,
                    request_deserializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.ExecutionReference.FromString,
                    response_serializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.ExecutionResult.SerializeToString,
            ),
            'DestroySession': grpc.unary_unary_rpc_method_handler(
                    servicer.DestroySession,
                    request_deserializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.DestroySessionRequest.FromString,
                    response_serializer=lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.DestroySessionResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'lagrl.sandbox.v1.Sandbox', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('lagrl.sandbox.v1.Sandbox', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Sandbox:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lagrl.sandbox.v1.Sandbox/CreateSession',
            lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.CreateSessionRequest.SerializeToString,
            lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.Session.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Execute(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lagrl.sandbox.v1.Sandbox/Execute',
            lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.ExecuteRequest.SerializeToString,
            lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.ExecutionReference.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lagrl.sandbox.v1.Sandbox/GetExecution',
            lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.ExecutionReference.SerializeToString,
            lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.ExecutionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DestroySession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/lagrl.sandbox.v1.Sandbox/DestroySession',
            lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.DestroySessionRequest.SerializeToString,
            lagrl_dot_sandbox_dot_proto_dot_sandbox__pb2.DestroySessionResult.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
